blueprint:
  name: Pilotage chauffage - Auxagama
  description: Gestion des différents modes de chauffage - Stop  Hors-gel  Auto confort
    Auto eco
  domain: automation

  input:
    entity_consigne:
      name: Consigne
      description: Champs d'entrée de la température de consigne (input number)
      selector:
        entity:
          domain: input_number
    entity_mode:
      name: Sélection du mode
      description: Entité de gestion du mode de gestion du chauffage (input_select)
      selector:
        entity:
          domain: input_select
    entity_schedule_confort:
      name: Schedule mode confort
      description: Entité générée par schedule pour la planification du mode confort
        (switch)
      selector:
        entity:
          domain: switch
    entity_schedule_eco:
      name: Schedule mode eco
      description: Entité générée par schedule pour la planification du mode eco (switch)
      selector:
        entity:
          domain: switch
    entity_thermostat_tpi:
      name: Thermostat
      description: Entité de gestion du thermostat TPI (automation)
      selector:
        entity:
          domain: automation

  source_url: https://github.com/XavLal/chauffage-home-assistant/blob/main/blueprint/chauffage_pilotage.yaml

# Température pour le hors gel 
variables: 
  temperature_hg: 10
  temperature_away: 17
  
alias: Pilotage chauffage
description: ''
trigger:
- platform: state
  entity_id: !input 'entity_mode'
condition: []
action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input 'entity_mode'
      state: Absent
    sequence:
    - service: automation.turn_on
      target:
        entity_id: !input 'entity_thermostat_tpi'
    - service: input_number.set_value
      data:
        value: '{{temperature_away}}'
      target:
        entity_id: !input 'entity_consigne'
    - service: switch.turn_off
      target:
        entity_id:
        - !input 'entity_schedule_eco'
        - !input 'entity_schedule_confort'
    - service: automation.turn_off
      target:
        entity_id: !input 'entity_thermostat_tpi'
  - conditions:
    - condition: state
      entity_id: !input 'entity_mode'
      state: Hors Gel
    sequence:
    - service: automation.turn_on
      target:
        entity_id: !input 'entity_thermostat_tpi'
    - service: input_number.set_value
      data:
        value: '{{temperature_hg}}'
      target:
        entity_id: !input 'entity_consigne'
    - service: switch.turn_off
      target:
        entity_id:
        - !input 'entity_schedule_eco'
        - !input 'entity_schedule_confort'
  - conditions:
    - condition: state
      entity_id: !input 'entity_mode'
      state: Confort
    sequence:
    - service: automation.turn_on
      target:
        entity_id: !input 'entity_thermostat_tpi'
    - service: switch.turn_on
      target:
        entity_id: !input 'entity_schedule_confort'
    - service: switch.turn_off
      target:
        entity_id:
        - !input 'entity_schedule_eco'
  - conditions:
    - condition: state
      entity_id: !input 'entity_mode'
      state: Eco
    sequence:
    - service: automation.turn_on
      target:
        entity_id: !input 'entity_thermostat_tpi'
    - service: switch.turn_off
      target:
        entity_id:
        - !input 'entity_schedule_confort'
    - service: switch.turn_on
      target:
        entity_id: !input 'entity_schedule_eco'
  default:
  - service: switch.turn_off
    target:
      entity_id:
      - !input 'entity_schedule_eco'
      - !input 'entity_schedule_confort'
  - service: automation.turn_on
    target:
      entity_id: !input 'entity_thermostat_tpi'
mode: single
